### ISSUE TITLE
silly-chooser

### ISSUE THREAD

**Issue by arily** [ArilyChan/qq-bot#6]
{ Error: Cannot find module 'sillyChooser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/arily/qq-bot/Plugins/exsper/sillyChooser/index.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Loader.loadLocalModule (/home/arily/qq-bot/node_modules/sb-qq-bot-framework/lib/Loader.js:85:27)
    at Loader.plugins.map (/home/arily/qq-bot/node_modules/sb-qq-bot-framework/lib/Loader.js:20:18)
    at Array.map (<anonymous>)
    at new Loader (/home/arily/qq-bot/node_modules/sb-qq-bot-framework/lib/Loader.js:12:13) code: 'MODULE_NOT_FOUND' }

**Comment by arily** [comment]
module is named as "sillychooser" not sillyChooser in package.json from repo ArilyChan/sillyChooser

**Comment by arily** [comment]
see pr https://github.com/ArilyChan/qq-bot/pull/7

**Comment by arily** [comment]
这个比较紧急我就先修了。
记得看一下错误及原因～

**Comment by Exsper** [comment]
thanks
